Table "tb_expedition" {
  "name_id" VARCHAR(255) [NOT NULL, UNIQUE]
  "name_spacecraft_id" VARCHAR(255) [NOT NULL]
  "start_flight_time" DATETIME2(0) [NOT NULL]
  "finish_flight_time" DATETIME2(0) [NOT NULL]
  "employee_expedition_id" VARCHAR(255) [NOT NULL]
}

Table "tb_expedition_bunch_planets" {
  "expedition_id" VARCHAR(255) [NOT NULL]
  "planet_id" INT [NOT NULL]
}

Table "tb_galaxy" {
  "id" INT [PRIMARY KEY]
  "mass" INT [NOT NULL]
  "core" BIT [NOT NULL]
  "movement_stars" INT [NOT NULL]
  "name" VARCHAR(255) [NOT NULL]
}

Table "tb_planet_system" {
  "id" INT [PRIMARY KEY]
  "galaxy_id" INT [NOT NULL]
  "name" VARCHAR(255)
}

Table "tb_stars" {
  "id" INT [PRIMARY KEY]
  "stars_system_id" INT [NOT NULL, UNIQUE]
}

Table "tb_planet" {
  "id" INT [PRIMARY KEY]
  "stars_system_id" INT [NOT NULL, UNIQUE]
}

Table "tb_spacecraft" {
  "name_id" VARCHAR(255) [NOT NULL, UNIQUE]
  "break_spacecraft" BIT [NOT NULL]
}

Table "tb_employee_expedition" {
  "name_id" VARCHAR(255)  [NOT NULL, UNIQUE]
  "employee_expedition_id" VARCHAR(255) [NOT NULL]
}

Table "tb_employee" {
  "id" INT [PRIMARY KEY]
  "email_address" VARCHAR(255) [NOT NULL]
  "name" VARCHAR(255) [NOT NULL]
  "phone" INT [NOT NULL]
  "position" VARCHAR(255) [NOT NULL]
}

Ref:"tb_expedition_bunch_planets"."expedition_id" < "tb_expedition"."name_id"

Ref:"tb_spacecraft"."name_id" < "tb_expedition"."name_spacecraft_id"

Ref:"tb_employee_expedition"."name_id" < "tb_expedition"."employee_expedition_id"

Ref:"tb_expedition_bunch_planets"."planet_id" < "tb_planet"."id"

Ref:"tb_planet_system"."galaxy_id" < "tb_galaxy"."id"

Ref:"tb_planet_system"."id" < "tb_stars"."stars_system_id"

Ref:"tb_planet_system"."id" < "tb_planet"."stars_system_id"

Ref:"tb_employee_expedition"."employee_expedition_id" < "tb_employee"."id"